### ISSUE TITLE
Tracking: Twitter Spaces Work

### ISSUE THREAD

**Issue by LexaMichaelides** [hyphacoop/cosmos-organizing#67]
This issue tracks sub-tasks relating to our prep and post work for the Twitter Spaces event hosted by Hypha to engage with the Cosmos Hub community about our upcoming community spend proposal to activate the Discourse forum. 

It will be ready to close when: The Twitter Spaces convo is finished and notes have been uploaded. 

### Relevant links
- [Original forum post](https://forum.cosmos.network/t/proposal-draft-use-the-forum-to-improve-governance-process/5530/8)
- [Community Spending Pool Proposal Draft](https://docs.google.com/document/d/11TmBSltGiZCRlHC-T77W_vmSnF8sV9SrZmxizZjueDI/edit?usp=sharing)

**Cosmos brand**
- [Arena Cosmos brand](https://www.are.na/share/ttajjNH)
- [Cosmos Presskit](https://v1.cosmos.network/presskit) 
- [Cosmos Visual Identity](https://v1.cosmos.network/design)

**Communal work (e.g., During meetings, group calls)**
- [x] Draft front matter for the proposal post in Forum
- [x] Confirm necessary participants in Twitter Spaces (Hub team, Hypha, stakefish)
- [x] Prep Twitter Spaces convo agenda and host notes
- [x]  Invite people to Twitter Spaces event

**Mai**
- [x] Blog post: Context and background on proposal, who is Hypha
- [x] Twitter banner announcing Twitter spaces convo (headlining Udit, Mai, Daniel, hopefully Billy or Sam)
- [x] Draft tweet thread re: proposal
- [x] Tweet out thread from Hypha account

**Udit**
- [x] Get access to Hypha Twitter and give to Mai and Lexa
- [x] Get Twitter

**Lexa**
- [x] Get Twitter
- [x] Twitter Spaces logistics research
- [x] Draft agenda for Twitter spaces
- [ ]  Blog post: FAQ and recap from the Twitter Space convo

**External tracking**
- [x] [stakefish] Invite people to Twitter Spaces event
- [x] [Daniel] Have stakefish team record Twitter Space convo using OBS
