### ISSUE TITLE
Tracking: Community Spend Proposal Edits

### ISSUE THREAD

**Issue by LexaMichaelides** [hyphacoop/cosmos-organizing#68]
This issue tracks sub-tasks relating to work on the community spend proposal to create a multisig in order to activate and steward the Cosmos Hub Discourse forum.

It will be ready to close when: The proposal has moved on-chain and can no longer be refined or edited.

### Relevant links
- [Original forum post](https://forum.cosmos.network/t/proposal-draft-use-the-forum-to-improve-governance-process/5530/8)
- [Community Spending Pool Proposal Draft](https://docs.google.com/document/d/11TmBSltGiZCRlHC-T77W_vmSnF8sV9SrZmxizZjueDI/edit?usp=sharing)

**Communal work (e.g., During meetings, group calls)**
- [x] Tighten up forum post
- [x] Make forum post

**Mai**
- [ ]  Wordsmith and propose disclosure

**Udit**
- [ ] Post disclosure to forum

**Lexa**
- [ ] 

**External tracking**
- [ ]

**Comment by uditvira** [comment]
Fri 11 Feb - Tweet promo
Tues 15 Feb - Last call
Thurs Feb 17 - Hopefully post goes on chain
